import { poppins } from '@/styles/fonts'
import './globals.css'
import type { Metadata } from 'next'
import TopBar from '@/components/top-bar/top-bar'
import SideBar from '@/components/side-bar/side-bar'


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body style={poppins.style}>
                <TopBar />

                <SideBar />

                {children}
            </body>
        </html>
    )
}
