'use client'
import { poppins } from '@/styles/fonts'
import './globals.css'
import type { Metadata } from 'next'
import TopBar from '@/components/top-bar/top-bar'
import SideBar from '@/components/side-bar/side-bar'
import { useState } from 'react'
import Form from '@/components/form/form'


// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const [isFormOpen, setIsFormOpen] = useState(false);

    const click = () => {
        setIsFormOpen(!isFormOpen)
    }


    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
            </head>
            <body style={poppins.style}>
                <TopBar />

                <SideBar />

                <Form open={isFormOpen} viewModalClick={click} />

                {children}
            </body>
        </html>
    )
}
